name: Trigger auto deployment for demogeneratorserver

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/demogeneratorserver-AutoDeployTrigger-da22219d-4301-4239-9e24-1e9cad5eea3e.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.DEMOGENERATORSERVER_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.DEMOGENERATORSERVER_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.DEMOGENERATORSERVER_AZURE_SUBSCRIPTION_ID }}

      - name: Build and deploy Container App
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          dockerfilePath: Dockerfile   # change if your Dockerfile is not at repo root
          acrName: demogeneratoracr     # this is the ACR resource name, not the login server
          containerAppName: demogeneratorserver
          resourceGroup: codebeamer-presales
          imageToBuild: demogeneratoracr.azurecr.io/demogeneratorserver:${{ github.sha }}
          imageToDeploy: demogeneratoracr.azurecr.io/demogeneratorserver:latest
          targetLabel: latest



